export const Constants = {
  SET_FILTERS: 'SET_FILTERS',
  FILTER_SHIPMENTS: 'FILTER_FILTERS',
  SUCCESS_FILTER_SHIPMENTS: 'SUCCESS_FILTER_SHIPMENTS',
  FAIL_FILTER_SHIPMENTS: 'FAIL_FILTER_SHIPMENTS',
  FETCH_SHIPMENTS: 'FETCH_FILTERS',
  SUCCESS_FETCH_SHIPMENTS: 'SUCCESS_FETCH_SHIPMENTS',
  FAIL_FETCH_SHIPMENTS: 'FAIL_FETCH_SHIPMENTS',
  CLEAR_FILTER_SHIPMENTS: 'CLEAR_FILTER_SHIPMENTS'
}
