export const Constants = {
  SET_FILTERS: 'SET_FILTERS',
  FILTER_SHIPMENTS: 'FILTER_FILTERS',
  SUCCESS_FILTER_SHIPMENTS: 'SUCCESS_FILTER_SHIPMENTS',
  FAIL_FILTER_SHIPMENTS: 'FAIL_FILTER_SHIPMENTS',
  FETCH_SHIPMENTS: 'FETCH_FILTERS',
  SUCCESS_FETCH_SHIPMENTS: 'SUCCESS_FETCH_SHIPMENTS',
  FAIL_FETCH_SHIPMENTS: 'FAIL_FETCH_SHIPMENTS',
  CLEAR_FILTER_SHIPMENTS: 'CLEAR_FILTER_SHIPMENTS',
  GET_CITIES: 'GET_CITIES',
  SUCCESS_GET_CITIES: 'SUCCESS_GET_CITIES',
  FAIL_GET_CITIES: 'FAIL_GET_CITIES',
  GET_STATUS: 'GET_STATUS',
  SUCCESS_GET_STATUS: 'SUCCESS_GET_STATUS',
  FAIL_GET_STATUS: 'FAIL_GET_STATUS',
  GET_CUSTOMER_STATUS: 'GET_CUSTOMER_STATUS',
  SUCCESS_GET_CUSTOMER_STATUS: 'SUCCESS_GET_CUSTOMER_STATUS',
  FAIL_GET_CUSTOMER_STATUS: 'FAIL_GET_CUSTOMER_STATUS'
}
